### PR TITLE
ThatOneGuy wanted a sound

### PR DESCRIPTION
**Pull request by W4rd3nn**
ok i did it yay.

### CODE REVIEW

**Comment by Techbot121** [comment]
umm why not just commit directly?

**Comment by suchipi** [comment]
you know that by default this sends an email to everyone in the metastruct team right @W4rd3nn

**Comment by SpiralP** [comment]
shame on you

**Comment by Techbot121** [comment]
:rage1:

**Comment by W4rd3nn** [comment]
lazy

**Comment by LUModder** [comment]
I've been telling you to direct commit.

**Pull request merged**
