### PR TITLE
Master

### PR DESCRIPTION
**Pull request by MrSpore**
Added Some Hellsing Episode 6 Quotes

### CODE REVIEW

**Comment by SpiralP** [comment]
I don't think you meant to remove woomy

**Comment by MrSpore** [comment]
Sorry, new to doing github tasks, still trying to figure out everything

**Comment by SpiralP** [comment]
ugh github is so hard to use, I can't figure how to use their site to "compare" going from you to Metastruct

**Comment by SpiralP** [comment]
try going to https://github.com/MrSpore/garrysmod-chatsounds/tree/267ac1b26481bbeb08de8834ae15b10a108a2f0e
and clicking "new pull request" myabe

**Comment by SpiralP** [comment]
if you can get to the command line you could like `git reset --hard HEAD~1` then `git push --force`

**Pull request closed without merging**
