### PR TITLE
Added mainly Skyrim stuff

### PR DESCRIPTION
**Pull request by 0x098**
For casual chatter

### CODE REVIEW

**Comment by Tenrys** [comment]
a lot of this isn't just for "casual chatter"

**Comment by notcake** [comment]
1. Too many sounds
2. Use `git rebase -i` to clean up the commit history
3. What is `sound/chatsounds/autoadd/niccep/stfu.ogg`. If it's from somewhere, categorize it properly.
4. `All checks have failed`
5. Too many sounds

**Comment by SpiralP** [comment]
I don't think they're in the right places, for example `sound/chatsounds/autoadd/skyrim/bandit/gonna rip you open.ogg` will only play if you say "bandit" in chat and NOT "gonna rip you open"

You could maybe move the folders in skyrim to like `sound/chatsounds/autoadd/skyrim_bandit` and such

**Comment by SpiralP** [comment]
Also, the numbered ones like `sound/chatsounds/autoadd/skyrim/bandit/skyrim bandit groan10.ogg` should be moved to `sound/chatsounds/autoadd/skyrim_bandit/skyrim bandit groan/skyrim bandit groan10.ogg` so you only have to say "skyrim bandit groan" and it will choose a random one from that folder

**Comment by SpiralP** [comment]
https://github.com/Metastruct/garrysmod-chatsounds/tree/master/sound/chatsounds/autoadd/theoffice here's an example folder how the structure should look like

**Pull request closed without merging**
