### PR TITLE
Only stop all sounds on other players if they allow it

### PR DESCRIPTION
**Pull request by danielga**
Stop all sounds if you sh'd yourself or if the other players have chatsounds_allow_stopsounds set to 1 (defaulted to 0).

### CODE REVIEW

**Comment by PotcFdk** [comment]
Should this default to 0?

**Comment by danielga** [comment]
Besides being an easily abusable and spammable feature, it doesn't make sense to me to allow people to stop every sound on other players.

**Comment by Datamats** [comment]
I agree, even as one guy does not want to listen to a chatsound does not mean everyone else agree

**Comment by PotcFdk** [comment]
Note that this was merged but then the behavior was changed to default to 1 in https://github.com/Metastruct/garrysmod-chatsounds/commit/234b488abc2df8d6cd8aa4f66d988ed8e93e7a5f

**Pull request merged**
