### PR TITLE
added a few old memes from flash video/game

### PR DESCRIPTION
**Pull request by bjoern90**
<insert zeeky word here>

### CODE REVIEW

**Comment by Etothepowerof26** [comment]
At least you ran the preprocessor.

**Comment by PotcFdk** [comment]
Personal folders make @KabusIblis cry, though :(

**Comment by KabusIblis** [comment]
@PotcFdk perhaps we should start forcing people to identify where the sounds came from so i dont have to manually figure out shit and slap it into the correct folders again

**Comment by PotcFdk** [comment]
```python
REJECT IF username CONTAINS soundsetname OR soundsetname CONTAINS username;
```

Though, really, this is a policy issue. There shouldn't be any huge problems to just declare "thou shalt not have personal folders" and give a deadline after which new folders are not accepted and old ones are just dropped. Unless, of course, @Etothepowerof26 comes along and merges it anyways.

**Comment by KabusIblis** [comment]
Perhaps we should set that as the policy moving forward, I'll eventually clean out chatsounds again becasue its bloated to shit

**Pull request merged**
