### PR TITLE
skyrim chatsounds

### PR DESCRIPTION
**Pull request by 0x098**
Try nr2
I hope these are not 'too many sounds' * 2.
The structure seems to be in order (imo).
Pardon my shortmindedness for not adapting to customs due to the tutorial file being 2 years old.
All files added under /skyrim

### CODE REVIEW

**Comment by 0x098** [comment]
understandable

**Comment by Etothepowerof26** [comment]
Nitpick: [this chatsounds that has its own folder.](https://github.com/0x098/garrysmod-chatsounds/tree/master/sound/chatsounds/autoadd/skyrim/im%20cumming)

**Comment by PotcFdk** [comment]
This should probably be a new preprocessor rule. ✌️

**Comment by 0x098** [comment]
Excuse my late action but I believe it fits now.

**Comment by Etothepowerof26** [comment]
Seems good enough.

**Comment by Zeni44** [comment]
I still don't think we need the majority of these

I fail to see why we need like 200+ skyrim sounds but since you already decided to merge it whatever

**Comment by Etothepowerof26** [comment]
Yeah you're probably right about the fact that we dont need all these chatsounds, but its 3.8x less sounds than the previous pull request. I can revert if you really want me to

**Pull request merged**
