### PR TITLE
add revenge (minecraft) chatsounds and etc

### PR DESCRIPTION
**Pull request by no-boot-device**
im sorry for putting more on here but 

then again this shouldn't be as much of a grueling task seeing as i know how to preprocess now

this should add some words that only `christian_caller` has rn lul

### CODE REVIEW

**Comment by no-boot-device** [comment]
ah shit i trade one fuck up out for another

the last three are the new ones

**Comment by KabusIblis** [comment]
Please do not pollute chatsounds with personal folders, I have done multiple chatsounds organisations manually before because people want to slap stuff into personal folders and I am not doing it again.

Whats with the multiple commits? All you need to do is follow the guide and commit when they all work, use the preprocessor if you are not sure or follow the guide.

**Comment by no-boot-device** [comment]
ah, i saw other personal folders and thought that was okay. good to know

it's to split the categories into different commits, i guess? i never really thought about why i was doing it

**Comment by Zeni44** [comment]
> Whats with the multiple commits? All you need to do is follow the guide and commit when they all work, use the preprocessor if you are not sure or follow the guide.

If you can't avoid it then refer to [git rebase](https://git-scm.com/docs/git-rebase)

**Comment by no-boot-device** [comment]
okay i think it's fixed now

**Pull request merged**
