### PR TITLE
Top gearathon streak #1

### PR DESCRIPTION
**Pull request by Kaspatik**
I have plans in the future for way more than rn with this, but I think it'll do.

### CODE REVIEW

**Comment by Kaspatik** [comment]
Big but the last update for this pull request. If there are any other complaints, would be nice to resolve 'em since this where I'll be wrapping up on this, and move onto other stuff.

**Comment by 0x098** [comment]
is it safe to assume the missing cocks were simply moved?

**Comment by Kaspatik** [comment]
Not sure what exactly you mean by that?

**Comment by 0x098** [comment]
these specific files? or am i tweakin
2704231953chrome_FdRNUbVSKE

**Comment by Kaspatik** [comment]
It might be the re-exporting that I was doing that causes it like that, they are still in the same folder.

**Pull request merged**
