### PR TITLE
Reorganising Chatsounds

### PR DESCRIPTION
**Pull request by KabusIblis**
This isn't quite complete but I might as well send a pull request

As some may know I've been reorganizing chatsounds due to the abundance of unorganized files being placed in new folders or wrong folders, hopefully this can address that

Some OGG files may be deleted, either due to a mistake or due to them being too long for any practical use

Doesn't have to be merged and can be abandoned if people deem it useless to organize this mess 👍

### CODE REVIEW

**Comment by notcake** [comment]
:+1:

**Comment by Techbot121** [comment]
this is what boredom does to you :+1:

**Comment by danielga** [comment]
Y'all don't know, the worlds about to end, the worlds about to end, the worlds about to end.

**Comment by KabusIblis** [comment]
you can blame python for not giving me much to do mapwise 👍

**Comment by ToastyEngineer** [comment]
you must have been really bored

**Comment by TrenchFroast** [comment]
[!](https://b.catgirlsare.sexy/6Qhi.png)

:eyes:

**Comment by TrenchFroast** [comment]
image
:eyes:

**Comment by LUModder** [comment]
👀

**Comment by LUModder** [comment]
!(https://my.mixtape.moe/agcjbm.png)[]

are you fucking serious

👎

**Comment by ToastyEngineer** [comment]
image

**Comment by KabusIblis** [comment]
:+1:

**Comment by Biomechd** [comment]
did you delete "you are dead/ded, not big surprise"?

**Comment by LUModder** [comment]
worst commit 2k16

proof meta has gone to shit since i left

**Comment by KabusIblis** [comment]
that's a tf2 chatsound @Biomechd

**Comment by Tenrys** [comment]
@LUModder kys

**Comment by TW1STaL1CKY** [comment]
oh no sound files have been deleted!!!!

**Comment by LUModder** [comment]
@Tenrys perfect example thanks

**Comment by KabusIblis** [comment]
@LUModder please tell me how you made meta good with your edits of existing work that others have done 😊

**Comment by Tenrys** [comment]
https://files.tenrys.pw/RVT2MGP7.jpg

**Comment by Tenrys** [comment]
Flex

**Comment by Mikeai** [comment]
WAH

**Pull request merged**
