### PR TITLE
sa2 dub, hewwo, and two extra fesh pince soundbytes 

### PR DESCRIPTION
**Pull request by no-boot-device**
this took two hours but now you can piss on the moon

### CODE REVIEW

**Comment by Etothepowerof26** [comment]
The CI check errored with [invalid sample rate files](https://pastebin.com/vFgubPuE). 44100 hertz is the preferred sample rate of the pre-processor.

**Comment by no-boot-device** [comment]
I thiiiink I fixed it?

**Comment by no-boot-device** [comment]
Ah shit, got to fix those too. Hooold on.

**Comment by Etothepowerof26** [comment]
Here goes nothing.

**Comment by Zeni44** [comment]
thanks we really needed these, definitely gonna use them

**Comment by Etothepowerof26** [comment]
yes

**Comment by KabusIblis** [comment]
image

**Pull request merged**
