### PR TITLE
Wheatley Chatsounds

### PR DESCRIPTION
**Pull request by Joetrija**
Heres a link to wheatley chatsounds from team fortress 2. Some of metas chatsounds can be existed already but this is a complete different one. It has more chatsounds than others. Have fun.

[Wheatley and TF2 chatsounds.zip](https://github.com/Metastruct/garrysmod-chatsounds/files/3464845/Wheatley.and.TF2.chatsounds.zip)

### CODE REVIEW

**Comment by Techbot121** [comment]
since it's tf2 you could just add them to the list here https://github.com/Metastruct/garrysmod-chatsounds/tree/master/lua/chatsounds/lists_send/tf

**Comment by Joetrija** [comment]
Oops, well im just new to GitHub and idk how it works. xd

**Comment by SpiralP** [comment]
I think these files should go in this other repo https://github.com/PAC3-Server/chatsounds-valve-games

oh actually now that I'm looking at it, your zip file has the same files as https://github.com/PAC3-Server/chatsounds-valve-games/tree/master/tf2/items ?

**Comment by SpiralP** [comment]
in theory goluwa should generate all game chatsounds, but the code needs more work to mount portal 2 correctly and I don't think it's even working at all right now

**Pull request closed without merging**
