### PR TITLE
Japanese Chatsounds

### PR DESCRIPTION
**Pull request by EngineMachiner**
Do not sue ™

### CODE REVIEW

**Comment by PotcFdk** [comment]
You've managed to create a conflict, wow. I award you some points.

**Comment by PotcFdk** [comment]
Merged in 27465a1e25e4d50b0bf34c165ea9ac0fcd85da20

**Comment by PotcFdk** [comment]
Thanks. For your future contributions, can you please reset your master branch to the upstream mast branch? These PRs don't fast-forward and even conflict, like right now.

Something like this, executed in your local working copy, should work:

```
$ git remote add upstream https://github.com/Metastruct/garrysmod-chatsounds
$ git reset --hard upstream/master
```

After this, `git rev-parse --verify HEAD` should show the current commit hash (which you can see at the top of the upstream log [here](https://github.com/Metastruct/garrysmod-chatsounds/commits/master)).
Feel free to remove that remote afterwards (`git remote rm upstream`), if you don't need it.

Alternatively, if you're feeling especially lazy, delete your repo and re-fork it.

**Comment by EngineMachiner** [comment]
Ehhh, I tried to do the first but I couldn't. I can't understand github o_O

**Comment by Noiwex** [comment]
lrn2git

**Pull request closed without merging**
