### PR TITLE
Added ! to the beginning of files

### PR DESCRIPTION
**Pull request by blockmanbuster**

### CODE REVIEW

**Comment by Cynosphere** [comment]
There's no reason to do this

**Comment by Earu** [comment]
https://github.com/Earu/neo-chatsounds/commit/6dce220b84dadab66e5bd53ea7b5c6a3f611ce01

**Comment by Cynosphere** [comment]
I didn't realize this was a subfolder and didn't know that was a possible thing. I assumed that this was a misunderstanding of "i want louder sounds xd"

**Comment by Cynosphere** [comment]
I still think the entire change of this should've been discussed and agreed upon due to other uses outside of neo-chatsounds that now have to find this out and implement it themselves, but whatever. Just shows that nothing has properly changed.

**Pull request merged**
