### PR TITLE
Added many german memes

### PR DESCRIPTION
**Pull request by davue**
Just add it, it's awesome!

EDIT: Don't pull it, I fucked something up. Fixing...
EDIT2: Done. Ready to be merged.

### CODE REVIEW

**Comment by Tenrys** [comment]
nice, wasted space for anyone that isn't german

**Comment by ToastyEngineer** [comment]
How to waste space at incredible hihg speed.
Not everyone can understand german memes nor are they funny either ✌️

**Comment by Techbot121** [comment]
http://cs.3kv.in/?s=das%20bleibt%20alles%20so%20wies%20hier%20ist

**Comment by Techbot121** [comment]
@PotcFdk let's have language branches 🤔

**Comment by KabusIblis** [comment]
shouldn't chatsounds just stick to commonly used sounds rather than random things? half of the chatsounds that exist are barely used by people commonly.

**Comment by Mikeai** [comment]
Does this call for a revert, since this is such a huge commit of probably mostly unused sounds save for maybe a few, thats alooooot of wasted space

**Comment by KabusIblis** [comment]
alternatively a branch or fork (I was cleaning chatsounds for a while) with just common used chatsounds to reduce on wasted space ect

**Pull request merged**
