### PR TITLE
Bejeweled Twist Chatsounds

### PR DESCRIPTION
**Pull request by V1NAlt**
Files that have a "1" at the end can be renamed if needed. Had to put it in parts because of the 100 file limit.

### CODE REVIEW

**Comment by Etothepowerof26** [comment]
Wait a little bit until the preprocessor runs for @gmZynx 's chatsounds then I'll merge it

**Comment by Etothepowerof26** [comment]
Okay, here we go

**Comment by PotcFdk** [comment]
fyi, you generally don't need to wait, it shouldn't collide or anything

**Comment by V1NAlt** [comment]
Might need to rename a couple of chatsounds in that folder. Two I forgot to rename to not have an underscore in them.

**Pull request merged**
