### PR TITLE
added more sounds

### PR DESCRIPTION
**Pull request by Ornstein0941**
i removed some sounds i added before

### CODE REVIEW

**Comment by Ornstein0941** [comment]
fuck you warden

**Comment by W4rd3nn** [comment]
gg you need to resolve conflicts n shit dawg

**Comment by PotcFdk** [comment]
* Less bad words in the commit messages
* Rebase your commits onto our master branch or nobody is going to care enough about this PR
* While you're at it, squash the commits. You're adding at least one sound that you remove in a later commit. This is completly unnecessary.

**Comment by Ornstein0941** [comment]
alright thanks for the information i will work on it

**Pull request closed without merging**
