### PR TITLE
idk some youtube

### PR DESCRIPTION
**Pull request by Nyaako**
yeah

### CODE REVIEW

**Comment by Noiwex** [comment]
how recognizable is this

**Comment by Nyaako** [comment]
how recognisable are half the gmod shatsounds?, besides people seem to like them anyway

**Comment by Tenrys** [comment]
Only "nut" and "begone thot" are good, rest is really bad imo
"What did you say" already exists in separated chatsounds

**Comment by KabusIblis** [comment]
seems like i need to go purge personal folders again

**Pull request closed without merging**
