### PR TITLE
pilalla

### PR DESCRIPTION
**Pull request by Vahinkolaukausosuma**

### CODE REVIEW

**Comment by Techbot121** [comment]
#

**Comment by SpiralP** [comment]
remove `chatsounds-preprocessor-cache` file please, it should be ignored not sure how this happened

**Comment by Vahinkolaukausosuma** [comment]
removed

**Comment by PotcFdk** [comment]
Next time please remove the entire commit out of the PR instead of adding garbage to the git object repo.

**Comment by PotcFdk** [comment]
nvm, garbage was already added in #123
Still interesting to see that this happens even though it's supposed to be ignored.

**Pull request merged**
