### PR TITLE
german memes

### PR DESCRIPTION
**Pull request by BoxedLight**
why was is rejected?

### CODE REVIEW

**Comment by BoxedLight** [comment]
Merge when?

**Comment by BoxedLight** [comment]
merge when?

**Comment by Mikeai** [comment]
Previously rejected for being there for a few months without comment or mention, these tend to get merged by demand or relevance which I didn't see either at the time. Jokes that are in a different language in probably exactly one use-case seem like a bad idea, but if this is something people want it can be merged.

**Comment by BoxedLight** [comment]
rejecting the pull request saying that nobody will use it kinda sets a chicken and egg problem. according to your logic then no chatsounds could be added because they didnt get used before. also there are pull request from other people that also had no comments and got merged so your argument saying that pull request need comments or relevance is kinda weak since only a small portion of meta is actually looking up pull requests on the chatsound github page let alone commenting them. why not merge and remove the chatsounds in a future commit if they are actually rarely used?

**Comment by Earu** [comment]
Names are not common words used for other chatsounds, the format of the files is ok, its only 4 sounds, merging.

**Comment by BoxedLight** [comment]
thank you

**Pull request merged**
