### PR TITLE
a pinch of chatsounds

### PR DESCRIPTION
**Pull request by ahamudo**
includes bumper to bumper unlimited mileage warranty

### CODE REVIEW

**Comment by bakapear** [comment]
why did you remove the bf3 sound files?

**Comment by SpiralP** [comment]
I moved your files around to where I assume you wanted
so if you type `touhou death` it will play `touhou/touhou death.ogg`
and `unlimited mileage bumper to bumper warranty` will play the file in `doug_demuro`

the file `chatsounds/autoadd/touhou/nuclearfusion.ogg` is kind of big, 600KB :p

**Comment by ahamudo** [comment]
@bakapear for some reason they wouldn't change from 48000hz, so had to remove em

**Comment by SpiralP** [comment]
want me to try changing the bf ones and committing them?

**Comment by ahamudo** [comment]
ye here you go
https://puu.sh/zD1Xd/b5573ffba1.ogg
https://puu.sh/zD1XF/fcaf84fa92.ogg
https://puu.sh/zD1XS/67d6dfb4c6.ogg
https://puu.sh/zD1Y3/77727a0018.ogg
https://puu.sh/zD1Yd/2af211a637.ogg

couldn't attach them because github

**Pull request merged**
