### PR TITLE
do you ever feel angry are you paralyzed by your anger

### PR DESCRIPTION
**Pull request by WicopeeDot**
_Do you ever feel angry? Are you paralyzed by your anger? Do you feel yourself with butterflies in your stomach a lot? You get headaches? Are you really frustrated? Do you ever get to the point where you gonna blow up? And you are afraid that if you blow up, you're gonna blow away all your friends and all your co-workers? Chances are. All of this behaviour is a symptom of the fact that you're not expressing your anger. We can certainly express our anger, if we handle our anger assertivley._

### CODE REVIEW

**Comment by Xerasin** [comment]
I feel this is way too long for one sound

**Comment by KabusIblis** [comment]
seperate this because a 30 second chatsound is too big

**Comment by WicopeeDot** [comment]
Closed.
Sound is way too long.

**Comment by Noiwex** [comment]
how could one man have slipped through your forces fingers time and time again how is it possible this is not some agent provocateur or highly trained assassin we are discussing gordon freeman is a theoretical physicist who had hardly earned the distinction of his ph d at the time of the black mesa incident i have good reason to believe that in the intervening years he was in a state that precluded further development of covert skills the man you have consistently failed to slow let alone capture is by all standards simply that an ordinary man how can you have failed to apprehend him

**Pull request closed without merging**
