### PR TITLE
you know what time it is

### PR DESCRIPTION
**Pull request by VoxxieBoxxie**

### CODE REVIEW

**Comment by PotcFdk** [comment]
This is introducing a personal folder, which is discouraged.

**Comment by VoxxieBoxxie** [comment]
> 
> 
> This is introducing a personal folder, which is discouraged.

Hopefully this works better for you.

**Comment by Cynosphere** [comment]
I'd put the "voxxie" one in `player_names` and the rest in `random_shit` personally, maybe "yankee with no brim" in `memes`

**Comment by VoxxieBoxxie** [comment]
> 
> 
> I'd put the "voxxie" one in `player_names` and the rest in `random_shit` personally, maybe "yankee with no brim" in `memes`

Good idea, Did so, Thanks.

**Comment by PotcFdk** [comment]
This looks wrong.
Please remember the two available path formats:
- chatsounds/autoadd/SETNAME/SOUNDNAME.ogg
- chatsounds/autoadd/SETNAME/SOUNDNAME/FILENAME.ogg

SETNAME is ignored. In the first case, SOUNDNAME.ogg would be triggered by SOUNDNAME. In the second case, FILENAME.ogg would be triggered by SOUNDNAME.

For example, chatsounds/autoadd/funny/player_names/voxxie.ogg makes no sense: The set name here is "funny", but the "voxxie.ogg" file would be triggered when someone types "player_names" in the chat.

**Comment by PotcFdk** [comment]
Also, please note that the "yankee with no brim" file has already been introduced [in this commit](https://github.com/Metastruct/garrysmod-chatsounds/pull/261/commits/78d0281cb4fdf6b02fd777824d631744b29bd23f).

**Comment by Mikeai** [comment]
Hierarchy is incorrect, as mentioned earlier, if you want to fix it, remove the folders inside the "funny" folder and put the other sounds in there. Folders inside folders should only be used when you want multiple sounds to trigger under one alias (what you type in chat for the sound).

Additionally, instead of making a whole new funny folder these sounds, put the sounds in folders that already exist, as mentioned the voxxie.ogg file should go in the player_names folder, and the undo sound can go into any appropriate folder (misc maybe?). As for yankee with no brim, you can get rid of that since #261 was merged recently.

Do that and i'll merge this.

**Comment by Zeni44** [comment]
This has been left untouched ever since. Feel free to create another pull request if the sounds are still desired.

I will close this.

**Pull request closed without merging**
