### PR TITLE
annie are you ok?

### PR DESCRIPTION
**Pull request by WicopeeDot**
__________

Added "chatsounds/sounds/autoadd/wicopee/annie are you ok.ogg"

### CODE REVIEW

**Comment by Techbot121** [comment]
old preprocessor

**Comment by Techbot121** [comment]
just commit without the lua files

**Comment by WicopeeDot** [comment]
you want me to remove wicopee.lua?

**Comment by WicopeeDot** [comment]
or i dont understand

**Comment by Techbot121** [comment]
yeah it will be autoprocessed

**Comment by WicopeeDot** [comment]
removed

**Comment by Techbot121** [comment]
well I actually meant the changes but this works too

**Comment by PotcFdk** [comment]
FYI old lists are not a problem, they will be replaced anyways.

**Pull request merged**
