### PR TITLE
Merge pull request

### PR DESCRIPTION
**Pull request by Black-Mage-8**

### CODE REVIEW

**Comment by SpiralP** [comment]
HUH

**Comment by Black-Mage-8** [comment]
yeah did it wrong lel. merged it correctly now.

**Comment by SpiralP** [comment]
I think you have access now, so you can just push directly to the repo if you want with `git push Metastruct` I think

**Comment by Black-Mage-8** [comment]
Nah. It told me to wait for acceptance...

**Comment by suchipi** [comment]
On my end it looks like the invite was sent and it's waiting for /you/ to accept it

**Comment by Black-Mage-8** [comment]
how do i accept it?

**Pull request closed without merging**
