### PR TITLE
a lot of chatsounds

### PR DESCRIPTION
**Pull request by loserVEVO**

### CODE REVIEW

**Comment by Tenrys** [comment]
**WHY WOULD YOU MAKE A COMMIT FOR EACH CHATSOUND?!!!!!**

**Comment by loserVEVO** [comment]
because uh, it doesnt really matter 😂

**Comment by Tenrys** [comment]
yes it does

**Comment by KabusIblis** [comment]
_why_

**Comment by SpiralP** [comment]
`dwarffortresstheme.ogg` is kind of long/big (4 minutes, ~2MB), I've tried ogg quality 0 in ffmpeg and still get 1MB :/
everything else looks like good size though

**Comment by Datamats** [comment]
I suggest we close this

**Pull request closed without merging**
