### PR TITLE
two chatsounds

### PR DESCRIPTION
**Pull request by EngineMachiner**
no no no
touch me please

### CODE REVIEW

**Comment by Mikeai** [comment]
I don't think we have standards for chatsounds, but if you're going to make commits this often, could you atleast have some more sounds to add?

**Comment by ToastyEngineer** [comment]
squash up the commits and it will be finee.

**Comment by EngineMachiner** [comment]
How do I?

**Comment by PotcFdk** [comment]
You can actually do it while merging, @ToastyEngineer 
@EngineMachiner More useful commit messages please.

**Comment by ToastyEngineer** [comment]
@PotcFdk but didn't I just do that

**Comment by PotcFdk** [comment]
@ToastyEngineer sorry, I meant @EngineMachiner in both cases.

**Comment by PotcFdk** [comment]
Hold on, no, I did in fact mean you. I didn't check whether you actually did do that or not.

**Comment by Mikeai** [comment]
We need less engineer-like personalities amongst the chatsounds contributors

**Pull request merged**
