### PR TITLE
blueangel, nestetrismusic(1-3), ...

### PR DESCRIPTION
**Pull request by Etothepowerof26**
Could un-comment the songs but it might be annoying
But for right now, its these

blueangel
nestetrismusic[1, 2, 3]
windowsxpsongpart[1, 2, 3]

### CODE REVIEW

**Comment by SpiralP** [comment]
No comments are allowed in the lists since they're automatically generated.  You shouldn't touch them manually 🐱

**Comment by SpiralP** [comment]
also wtf these files are huge, one is like 8MB

**Comment by Etothepowerof26** [comment]
Didn't know that. Thanks for telling me.

Giant size is because of it being a full song (was experimenting on my own)

**Comment by SpiralP** [comment]
`ffmpeg -i burnthismoment.ogg burnthismoment2.ogg` lowered it to be half the size, even without quality settings.  are you sure you chose low quality

**Comment by Etothepowerof26** [comment]
Oh, just realized that the 1mb+ songs are 192 Kbps 44100 Hz. Should I sample them down a bit?

**Comment by PotcFdk** [comment]
Bonus points for squashing.

**Comment by ToastyEngineer** [comment]
Minus points for it being bad music

**Comment by PotcFdk** [comment]
Jesus christ, this PR seems to be worse than expected.
The added sounds are literally the top 5 longest chatsounds that we currently have:
```
#1: chatsounds/autoadd/26e/burnthismoment.ogg : 385.09
#2: chatsounds/autoadd/26e/overtheflood.ogg : 383.014
#3: chatsounds/autoadd/26e/benzo.ogg : 371.109
#4: chatsounds/autoadd/26e/natureofdying.ogg : 360.303
#5: chatsounds/autoadd/26e/noangelshere.ogg : 334.621
```

@SpiralP what have you done

**Comment by Etothepowerof26** [comment]
you can delete them idc lol

**Pull request merged**
